[General]
__userfile__=true
backlightIdleness=50
backlightIdlenessOnBatteryDischarging=true
disableIdlenessWhenFullscreen=true
enableBatteryWatcher=true
enableExtMonLidClosedActions=false
enableIdlenessBacklightWatcher=false
enableIdlenessWatcher=true
enableLidWatcher=true
hibernateKeyAction=1
iconType=4
idlenessACAction=-1
idlenessACTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessBatteryAction=-1
idlenessBatteryTime=@Variant(\0\0\0\xf\0\r\xbb\xa0)
idlenessTime=@Variant(\0\0\0\xf\0\0\xea`)
lidClosedAcAction=4
lidClosedAction=1
lidClosedExtMonAcAction=-1
lidClosedExtMonAction=-1
powerKeyAction=3
powerLowAction=-1
powerLowLevel=10
powerLowWarning=60
runCheckLevel=1
showIcon=true
suspendKeyAction=4
