[General]
__userfile__=true
tool_bar_icon_size=22
wallpaper_override=false

[Palette]
base_color=#ffffff
highlight_color=#5294e2
highlighted_text_color=#ffffff
link_color=#0057ae
link_visited_color=#452886
text_color=#000000
tooltip_base_color=#000000
tooltip_text_color=#eefcff
window_color=#f5f6f7
window_text_color=#000000

[Qt]
font="Ubuntu,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
style=kvantum-dark
