[General]
__userfile__=true
panels=panel_left_monitor, panel_middle_monitor, panel_right_monitor

[desktopswitch]
alignment=Left

[mount]
alignment=Right

[panel_left_monitor]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=2
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=32
lineCount=1
lockPanel=false
opacity=100
panelSize=48
plugins=taskbar_left_monitor
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[taskbar_left_monitor]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=Icon
buttonWidth=64
closeOnMiddleClick=false
excludedList=
groupingEnabled=true
iconByClass=true
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=true
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=false
type=taskbar
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=1

[panel_middle_monitor]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=32
lineCount=1
lockPanel=false
opacity=100
panelSize=48
plugins=fancymenu, taskbar_middle_monitor, mount, tray, statusnotifier, worldclock
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[taskbar_middle_monitor]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=Icon
buttonWidth=64
closeOnMiddleClick=false
excludedList=
groupingEnabled=true
iconByClass=true
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=true
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=false
type=taskbar
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=1

[panel_right_monitor]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=1
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=32
lineCount=1
lockPanel=false
opacity=100
panelSize=48
plugins=taskbar_right_monitor
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[taskbar_right_monitor]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=Icon
buttonWidth=64
closeOnMiddleClick=false
excludedList=
groupingEnabled=true
iconByClass=true
raiseOnCurrentDesktop=false
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=true
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=false
type=taskbar
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=1

[tray]
alignment=Right

[worldclock]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=below
dateShowDoW=true
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=false
timePadHour=true
timeShowSeconds=true
timeZoneWheel=true
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
useAdvancedManualFormat=false
